import{withBusy as x}from"./downloads.js";const f=6,m=1.35,y=e=>Math.min(f,Math.max(t.min,e));let o,t;function r(){const{state:e}=t;t.stage.style.transform=`translate(calc(-50% + ${e.tx}px), calc(-50% + ${e.ty}px)) scale(${e.scale})`,t.zoom.textContent=`${Math.round(e.scale*100)}%`}function v(){const e=t.stage.querySelector("svg"),i=e&&e.viewBox&&e.viewBox.baseVal;if(!i||!i.width)return 1;const a=t.stage.clientWidth*(i.height/i.width);return Math.min(1,t.view.clientHeight*.96/a)}function g(){t.min=v(),t.state.scale=y(t.state.scale),r()}function p(){o.hidden=!0,document.removeEventListener("keydown",t.onKey),window.removeEventListener("resize",t.onResize)}function w(e,i){const a=new Map;let l=null,s=null,d=!1;e.addEventListener("pointerdown",n=>{if(a.set(n.pointerId,{x:n.clientX,y:n.clientY}),e.setPointerCapture(n.pointerId),d=!1,a.size===1)s={x:n.clientX,y:n.clientY,tx:t.state.tx,ty:t.state.ty},i.classList.add("grabbing");else if(a.size===2){s=null;const[u,b]=[...a.values()];l={dist:Math.hypot(u.x-b.x,u.y-b.y)||1,scale:t.state.scale}}}),e.addEventListener("pointermove",n=>{if(a.has(n.pointerId))if(a.set(n.pointerId,{x:n.clientX,y:n.clientY}),a.size===2&&l){const[u,b]=[...a.values()],h=Math.hypot(u.x-b.x,u.y-b.y)||1;t.state.scale=y(h/l.dist*l.scale),d=!0,r()}else s&&(t.state.tx=s.tx+(n.clientX-s.x),t.state.ty=s.ty+(n.clientY-s.y),Math.abs(n.clientX-s.x)+Math.abs(n.clientY-s.y)>3&&(d=!0),r())});const c=n=>{a.delete(n.pointerId),i.classList.remove("grabbing"),a.size<2&&(l=null),a.size===0&&(s=null,!d&&!o.hidden&&p())};e.addEventListener("pointerup",c),e.addEventListener("pointercancel",c),e.addEventListener("wheel",n=>{n.preventDefault(),t.state.scale=y(t.state.scale*(1-n.deltaY*.0015)),r()},{passive:!1}),e.addEventListener("dblclick",()=>{t.state.scale=t.state.scale>t.min?t.min:2.5,t.state.tx=0,t.state.ty=0,r()})}function z(){const e=document.createElement("div");e.className="lightbox",e.hidden=!0,e.innerHTML=`
    <div class="lb-bar">
      <span class="lb-title"></span>
      <button type="button" data-act="out" title="Zoom out">\u2212</button>
      <button type="button" data-act="reset" title="Reset zoom">100%</button>
      <button type="button" data-act="in" title="Zoom in">+</button>
      <button type="button" data-act="dl">\u2B07 Download</button>
      <button type="button" data-act="close" title="Close (Esc)">\u2715</button>
    </div>
    <div class="lb-view">
      <div class="lb-stage"></div>
    </div>
    <p class="lb-hint">Drag to pan \xB7 scroll or pinch to zoom \xB7 double-click to reset</p>`,document.body.appendChild(e);const i=e.querySelector(".lb-view"),a=e.querySelector(".lb-stage"),l=e.querySelector('[data-act="reset"]');return w(i,a),e.querySelector('[data-act="in"]').onclick=()=>{t.state.scale=y(t.state.scale*m),r()},e.querySelector('[data-act="out"]').onclick=()=>{t.state.scale=y(t.state.scale/m),r()},l.onclick=()=>{t.state.scale=t.min,t.state.tx=0,t.state.ty=0,r()},e.querySelector('[data-act="dl"]').onclick=s=>t.onDownload&&x(s.currentTarget,"Preparing\u2026",t.onDownload),e.querySelector('[data-act="close"]').onclick=p,{box:e,view:i,stage:a,zoom:l}}function E({title:e,svg:i,onDownload:a}){if(!o){const c=z();o=c.box,o._view=c.view,o._stage=c.stage,o._zoom=c.zoom}o.querySelector(".lb-title").textContent=e,o._stage.innerHTML=i,o.hidden=!1;const l=o._stage.querySelector("svg");l&&(l.style.minWidth="0");const s=c=>{c.key==="Escape"&&p()},d=g;t={state:{scale:1,tx:0,ty:0},min:1,stage:o._stage,view:o._view,zoom:o._zoom,onDownload:a,onKey:s,onResize:d},t.min=v(),t.state.scale=t.min,document.addEventListener("keydown",s),window.addEventListener("resize",d),r()}export{E as openLightbox};
